server:
  port: ${PORT:8080}

spring:
  application:
    name: jcroft
logging:
  level:
    com.hazelcast: DEBUG
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR
    com.hazelcast.cluster.impl.TcpIpJoiner: INFO
    c.h.i.p.InternalPartitionService: INFO
org.hibernate: DEBUG